name: Update XRP Data

on:
  schedule:
    - cron: "0 3 * * *"  # daily at 3am UTC
    - cron: '0 7 * * *'
    - cron: '0 2 * * *' # 17:00 UTC = 12:00 PM (noon) Central Time
    - cron: '0 17 * * *' # 17:00 UTC = 12:00 PM (noon) Central Time
    - cron: '0 23 * * *' # 17:00 UTC = 12:00 PM (noon) Central Time
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install pandas requests

      - name: Run collector
        run: python xrpl_data_collector.py

      - name: Commit data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/
          git commit -m "Update XRP rich list" || echo "No changes"
          git push
